# Generated by Django 3.1.4 on 2021-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=150, null=True)),
                ('classname', models.CharField(max_length=150)),
                ('members', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
    ]
